// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostLikeSuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostLikeSuccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
