// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostSearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostSearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keywords = 1;</code>
   */
  java.lang.String getKeywords();
  /**
   * <code>string keywords = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeywordsBytes();
}
