// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 blogpostID = 1;</code>
   */
  int getBlogpostID();

  /**
   * <code>int32 cid = 2;</code>
   */
  int getCid();

  /**
   * <code>string author = 3;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string comment = 4;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 4;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>bool positive = 5;</code>
   */
  boolean getPositive();
}
