// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.Blogpost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string author = 2;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 2;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string title = 3;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>bool important = 4;</code>
   */
  boolean getImportant();

  /**
   * <code>string description = 5;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .be.cloud.BlogpostComment comments = 6;</code>
   */
  java.util.List<be.cloud.BlogpostComment> 
      getCommentsList();
  /**
   * <code>repeated .be.cloud.BlogpostComment comments = 6;</code>
   */
  be.cloud.BlogpostComment getComments(int index);
  /**
   * <code>repeated .be.cloud.BlogpostComment comments = 6;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .be.cloud.BlogpostComment comments = 6;</code>
   */
  java.util.List<? extends be.cloud.BlogpostCommentOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .be.cloud.BlogpostComment comments = 6;</code>
   */
  be.cloud.BlogpostCommentOrBuilder getCommentsOrBuilder(
      int index);
}
