// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

/**
 * Protobuf type {@code be.cloud.BlogpostSearchResults}
 */
public  final class BlogpostSearchResults extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:be.cloud.BlogpostSearchResults)
    BlogpostSearchResultsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlogpostSearchResults.newBuilder() to construct.
  private BlogpostSearchResults(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlogpostSearchResults() {
    blogposts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlogpostSearchResults(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              blogposts_ = new java.util.ArrayList<be.cloud.Blogpost>();
              mutable_bitField0_ |= 0x00000001;
            }
            blogposts_.add(
                input.readMessage(be.cloud.Blogpost.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        blogposts_ = java.util.Collections.unmodifiableList(blogposts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.cloud.Blogdb.internal_static_be_cloud_BlogpostSearchResults_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.cloud.Blogdb.internal_static_be_cloud_BlogpostSearchResults_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.cloud.BlogpostSearchResults.class, be.cloud.BlogpostSearchResults.Builder.class);
  }

  public static final int BLOGPOSTS_FIELD_NUMBER = 1;
  private java.util.List<be.cloud.Blogpost> blogposts_;
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  public java.util.List<be.cloud.Blogpost> getBlogpostsList() {
    return blogposts_;
  }
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  public java.util.List<? extends be.cloud.BlogpostOrBuilder> 
      getBlogpostsOrBuilderList() {
    return blogposts_;
  }
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  public int getBlogpostsCount() {
    return blogposts_.size();
  }
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  public be.cloud.Blogpost getBlogposts(int index) {
    return blogposts_.get(index);
  }
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  public be.cloud.BlogpostOrBuilder getBlogpostsOrBuilder(
      int index) {
    return blogposts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < blogposts_.size(); i++) {
      output.writeMessage(1, blogposts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < blogposts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, blogposts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.cloud.BlogpostSearchResults)) {
      return super.equals(obj);
    }
    be.cloud.BlogpostSearchResults other = (be.cloud.BlogpostSearchResults) obj;

    boolean result = true;
    result = result && getBlogpostsList()
        .equals(other.getBlogpostsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBlogpostsCount() > 0) {
      hash = (37 * hash) + BLOGPOSTS_FIELD_NUMBER;
      hash = (53 * hash) + getBlogpostsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.cloud.BlogpostSearchResults parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.cloud.BlogpostSearchResults parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static be.cloud.BlogpostSearchResults parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.BlogpostSearchResults parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.cloud.BlogpostSearchResults prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code be.cloud.BlogpostSearchResults}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:be.cloud.BlogpostSearchResults)
      be.cloud.BlogpostSearchResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.cloud.Blogdb.internal_static_be_cloud_BlogpostSearchResults_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.cloud.Blogdb.internal_static_be_cloud_BlogpostSearchResults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.cloud.BlogpostSearchResults.class, be.cloud.BlogpostSearchResults.Builder.class);
    }

    // Construct using be.cloud.BlogpostSearchResults.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlogpostsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (blogpostsBuilder_ == null) {
        blogposts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        blogpostsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.cloud.Blogdb.internal_static_be_cloud_BlogpostSearchResults_descriptor;
    }

    @java.lang.Override
    public be.cloud.BlogpostSearchResults getDefaultInstanceForType() {
      return be.cloud.BlogpostSearchResults.getDefaultInstance();
    }

    @java.lang.Override
    public be.cloud.BlogpostSearchResults build() {
      be.cloud.BlogpostSearchResults result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.cloud.BlogpostSearchResults buildPartial() {
      be.cloud.BlogpostSearchResults result = new be.cloud.BlogpostSearchResults(this);
      int from_bitField0_ = bitField0_;
      if (blogpostsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          blogposts_ = java.util.Collections.unmodifiableList(blogposts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.blogposts_ = blogposts_;
      } else {
        result.blogposts_ = blogpostsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.cloud.BlogpostSearchResults) {
        return mergeFrom((be.cloud.BlogpostSearchResults)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.cloud.BlogpostSearchResults other) {
      if (other == be.cloud.BlogpostSearchResults.getDefaultInstance()) return this;
      if (blogpostsBuilder_ == null) {
        if (!other.blogposts_.isEmpty()) {
          if (blogposts_.isEmpty()) {
            blogposts_ = other.blogposts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBlogpostsIsMutable();
            blogposts_.addAll(other.blogposts_);
          }
          onChanged();
        }
      } else {
        if (!other.blogposts_.isEmpty()) {
          if (blogpostsBuilder_.isEmpty()) {
            blogpostsBuilder_.dispose();
            blogpostsBuilder_ = null;
            blogposts_ = other.blogposts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            blogpostsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlogpostsFieldBuilder() : null;
          } else {
            blogpostsBuilder_.addAllMessages(other.blogposts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      be.cloud.BlogpostSearchResults parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (be.cloud.BlogpostSearchResults) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<be.cloud.Blogpost> blogposts_ =
      java.util.Collections.emptyList();
    private void ensureBlogpostsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        blogposts_ = new java.util.ArrayList<be.cloud.Blogpost>(blogposts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.cloud.Blogpost, be.cloud.Blogpost.Builder, be.cloud.BlogpostOrBuilder> blogpostsBuilder_;

    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public java.util.List<be.cloud.Blogpost> getBlogpostsList() {
      if (blogpostsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blogposts_);
      } else {
        return blogpostsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public int getBlogpostsCount() {
      if (blogpostsBuilder_ == null) {
        return blogposts_.size();
      } else {
        return blogpostsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public be.cloud.Blogpost getBlogposts(int index) {
      if (blogpostsBuilder_ == null) {
        return blogposts_.get(index);
      } else {
        return blogpostsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder setBlogposts(
        int index, be.cloud.Blogpost value) {
      if (blogpostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogpostsIsMutable();
        blogposts_.set(index, value);
        onChanged();
      } else {
        blogpostsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder setBlogposts(
        int index, be.cloud.Blogpost.Builder builderForValue) {
      if (blogpostsBuilder_ == null) {
        ensureBlogpostsIsMutable();
        blogposts_.set(index, builderForValue.build());
        onChanged();
      } else {
        blogpostsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder addBlogposts(be.cloud.Blogpost value) {
      if (blogpostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogpostsIsMutable();
        blogposts_.add(value);
        onChanged();
      } else {
        blogpostsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder addBlogposts(
        int index, be.cloud.Blogpost value) {
      if (blogpostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogpostsIsMutable();
        blogposts_.add(index, value);
        onChanged();
      } else {
        blogpostsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder addBlogposts(
        be.cloud.Blogpost.Builder builderForValue) {
      if (blogpostsBuilder_ == null) {
        ensureBlogpostsIsMutable();
        blogposts_.add(builderForValue.build());
        onChanged();
      } else {
        blogpostsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder addBlogposts(
        int index, be.cloud.Blogpost.Builder builderForValue) {
      if (blogpostsBuilder_ == null) {
        ensureBlogpostsIsMutable();
        blogposts_.add(index, builderForValue.build());
        onChanged();
      } else {
        blogpostsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder addAllBlogposts(
        java.lang.Iterable<? extends be.cloud.Blogpost> values) {
      if (blogpostsBuilder_ == null) {
        ensureBlogpostsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blogposts_);
        onChanged();
      } else {
        blogpostsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder clearBlogposts() {
      if (blogpostsBuilder_ == null) {
        blogposts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        blogpostsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public Builder removeBlogposts(int index) {
      if (blogpostsBuilder_ == null) {
        ensureBlogpostsIsMutable();
        blogposts_.remove(index);
        onChanged();
      } else {
        blogpostsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public be.cloud.Blogpost.Builder getBlogpostsBuilder(
        int index) {
      return getBlogpostsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public be.cloud.BlogpostOrBuilder getBlogpostsOrBuilder(
        int index) {
      if (blogpostsBuilder_ == null) {
        return blogposts_.get(index);  } else {
        return blogpostsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public java.util.List<? extends be.cloud.BlogpostOrBuilder> 
         getBlogpostsOrBuilderList() {
      if (blogpostsBuilder_ != null) {
        return blogpostsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blogposts_);
      }
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public be.cloud.Blogpost.Builder addBlogpostsBuilder() {
      return getBlogpostsFieldBuilder().addBuilder(
          be.cloud.Blogpost.getDefaultInstance());
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public be.cloud.Blogpost.Builder addBlogpostsBuilder(
        int index) {
      return getBlogpostsFieldBuilder().addBuilder(
          index, be.cloud.Blogpost.getDefaultInstance());
    }
    /**
     * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
     */
    public java.util.List<be.cloud.Blogpost.Builder> 
         getBlogpostsBuilderList() {
      return getBlogpostsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        be.cloud.Blogpost, be.cloud.Blogpost.Builder, be.cloud.BlogpostOrBuilder> 
        getBlogpostsFieldBuilder() {
      if (blogpostsBuilder_ == null) {
        blogpostsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            be.cloud.Blogpost, be.cloud.Blogpost.Builder, be.cloud.BlogpostOrBuilder>(
                blogposts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        blogposts_ = null;
      }
      return blogpostsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:be.cloud.BlogpostSearchResults)
  }

  // @@protoc_insertion_point(class_scope:be.cloud.BlogpostSearchResults)
  private static final be.cloud.BlogpostSearchResults DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.cloud.BlogpostSearchResults();
  }

  public static be.cloud.BlogpostSearchResults getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlogpostSearchResults>
      PARSER = new com.google.protobuf.AbstractParser<BlogpostSearchResults>() {
    @java.lang.Override
    public BlogpostSearchResults parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlogpostSearchResults(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlogpostSearchResults> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlogpostSearchResults> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.cloud.BlogpostSearchResults getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

