// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostListRequest)
    com.google.protobuf.MessageOrBuilder {
}
