// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
