// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public final class Blogdb {
  private Blogdb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_Blogpost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_Blogpost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostComment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostComment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostAddSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostAddSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostCommentAddSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostCommentAddSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostSearchResults_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostSearchResults_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_BlogpostLikeSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_BlogpostLikeSuccess_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014blogdb.proto\022\010be.cloud\"\212\001\n\010Blogpost\022\n\n" +
      "\002id\030\001 \001(\005\022\016\n\006author\030\002 \001(\t\022\r\n\005title\030\003 \001(\t" +
      "\022\021\n\timportant\030\004 \001(\010\022\023\n\013description\030\005 \001(\t" +
      "\022+\n\010comments\030\006 \003(\0132\031.be.cloud.BlogpostCo" +
      "mment\"e\n\017BlogpostComment\022\022\n\nblogpostID\030\001" +
      " \001(\005\022\013\n\003cid\030\002 \001(\005\022\016\n\006author\030\003 \001(\t\022\017\n\007com" +
      "ment\030\004 \001(\t\022\020\n\010positive\030\005 \001(\010\"\030\n\nBlogpost" +
      "ID\022\n\n\002id\030\001 \001(\005\"%\n\022BlogpostAddSuccess\022\017\n\007" +
      "success\030\001 \001(\010\",\n\031BlogpostCommentAddSucce" +
      "ss\022\017\n\007success\030\001 \001(\010\"\025\n\023BlogpostListReque" +
      "st\"5\n\014BlogpostList\022%\n\tblogposts\030\001 \003(\0132\022." +
      "be.cloud.Blogpost\")\n\025BlogpostSearchReque" +
      "st\022\020\n\010keywords\030\001 \001(\t\">\n\025BlogpostSearchRe" +
      "sults\022%\n\tblogposts\030\001 \003(\0132\022.be.cloud.Blog" +
      "post\"&\n\023BlogpostLikeSuccess\022\017\n\007success\030\001" +
      " \001(\0102\276\003\n\013BlogService\022?\n\013addBlogpost\022\022.be" +
      ".cloud.Blogpost\032\034.be.cloud.BlogpostAddSu" +
      "ccess\0227\n\013getBlogpost\022\024.be.cloud.Blogpost" +
      "ID\032\022.be.cloud.Blogpost\022T\n\022addBlogpostCom" +
      "ment\022\031.be.cloud.BlogpostComment\032#.be.clo" +
      "ud.BlogpostCommentAddSuccess\022E\n\014getBlogp" +
      "osts\022\035.be.cloud.BlogpostListRequest\032\026.be" +
      ".cloud.BlogpostList\022S\n\017searchBlogposts\022\037" +
      ".be.cloud.BlogpostSearchRequest\032\037.be.clo" +
      "ud.BlogpostSearchResults\022C\n\014likeBlogpost" +
      "\022\024.be.cloud.BlogpostID\032\035.be.cloud.Blogpo" +
      "stLikeSuccessB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_be_cloud_Blogpost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_cloud_Blogpost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_Blogpost_descriptor,
        new java.lang.String[] { "Id", "Author", "Title", "Important", "Description", "Comments", });
    internal_static_be_cloud_BlogpostComment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_cloud_BlogpostComment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostComment_descriptor,
        new java.lang.String[] { "BlogpostID", "Cid", "Author", "Comment", "Positive", });
    internal_static_be_cloud_BlogpostID_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_be_cloud_BlogpostID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_be_cloud_BlogpostAddSuccess_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_be_cloud_BlogpostAddSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostAddSuccess_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_be_cloud_BlogpostCommentAddSuccess_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_be_cloud_BlogpostCommentAddSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostCommentAddSuccess_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_be_cloud_BlogpostListRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_be_cloud_BlogpostListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_be_cloud_BlogpostList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_be_cloud_BlogpostList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostList_descriptor,
        new java.lang.String[] { "Blogposts", });
    internal_static_be_cloud_BlogpostSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_be_cloud_BlogpostSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostSearchRequest_descriptor,
        new java.lang.String[] { "Keywords", });
    internal_static_be_cloud_BlogpostSearchResults_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_be_cloud_BlogpostSearchResults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostSearchResults_descriptor,
        new java.lang.String[] { "Blogposts", });
    internal_static_be_cloud_BlogpostLikeSuccess_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_be_cloud_BlogpostLikeSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_BlogpostLikeSuccess_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
