// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogdb.proto

package be.cloud;

public interface BlogpostListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.BlogpostList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  java.util.List<be.cloud.Blogpost> 
      getBlogpostsList();
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  be.cloud.Blogpost getBlogposts(int index);
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  int getBlogpostsCount();
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  java.util.List<? extends be.cloud.BlogpostOrBuilder> 
      getBlogpostsOrBuilderList();
  /**
   * <code>repeated .be.cloud.Blogpost blogposts = 1;</code>
   */
  be.cloud.BlogpostOrBuilder getBlogpostsOrBuilder(
      int index);
}
